apiVersion: v1
kind: Service
metadata:
  name: ats-service-lb
  namespace: ats-space
spec:
  selector:
    app: ats-app
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30080
  type: LoadBalancer